// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"gorm.io/gorm"
	"news/api"
	"news/repository"
	"news/service"
)

// Injectors from wire.go:

func InitNewsArticleAPI(db *gorm.DB) api.NewsArticleAPI {
	iNewsArticleRepository := repository.NewNewsArticleRepository(db)
	iNewsArticleService := service.NewNewsArticleService(iNewsArticleRepository)
	newsArticleAPI := api.NewNewsArticleAPI(iNewsArticleService)
	return newsArticleAPI
}

func InitNewsCommentAPI(db *gorm.DB) api.NewsCommentAPI {
	iNewsCommentRepository := repository.NewNewsCommentRepository(db)
	iNewsCommentService := service.NewNewsCommentService(iNewsCommentRepository)
	newsCommentAPI := api.NewNewsCommentAPI(iNewsCommentService)
	return newsCommentAPI
}

func InitNewsSubscriptionAPI(db *gorm.DB) api.NewsSubscriptionAPI {
	iNewsSubscriptionRepository := repository.NewNewsSubscriptionRepository(db)
	iNewsSubscriptionService := service.NewNewsSubscriptionService(iNewsSubscriptionRepository)
	newsSubscriptionAPI := api.NewNewsSubscriptionAPI(iNewsSubscriptionService)
	return newsSubscriptionAPI
}
