BASE = "http://localhost:5000"

API = "/api/users"

GET_USER_BY_ID = "/getById"
REGISTER = "/register"
GET_VERIFICATION_CODE = "/getVerificationCode"
VERIFY_ACCOUNT = "/verifyAccount"
ADD_EMPLOYEE_AND_ADMIN = "/addEmployeeAndAdmin"
GET_ALL_REGISTERED_USERS = "/getAllRegisteredUsers"
GET_NUMBER_OF_RECORDS_REGISTERED_USERS = "/getNumberOfRecordsRegisteredUsers"
SEARCH_REGISTERED_USERS = "/searchRegisteredUsers"
GET_NUMBER_OF_RECORDS_REGISTERED_USERS_SEARCH = "/getNumberOfRecordsRegisteredUsersSearch"
UPDATE = "/update"
CHANGE_PASSWORD = "/changePassword"
