// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"comment-and-rating/api"
	"comment-and-rating/repository"
	"comment-and-rating/service"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitProductCommentAPI(db *gorm.DB) api.ProductCommentAPI {
	iProductCommentRepository := repository.NewProductCommentRepository(db)
	iProductCommentService := service.NewProductCommentService(iProductCommentRepository)
	productCommentAPI := api.NewProductCommentServiceAPI(iProductCommentService)
	return productCommentAPI
}
