// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"gorm.io/gorm"
	"product/api"
	"product/repository"
	"product/service"
)

// Injectors from wire.go:

func InitVideoGameAPI(db *gorm.DB) api.VideoGameAPI {
	iVideoGameRepository := repository.NewVideoGameRepository(db)
	iVideoGameService := service.NewVideoGameService(iVideoGameRepository)
	videoGameAPI := api.NewVideoGameAPI(iVideoGameService)
	return videoGameAPI
}
