// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"gorm.io/gorm"
	"product/api"
	"product/repository"
	"product/service"
)

// Injectors from wire.go:

func InitVideoGameAPI(db *gorm.DB) api.VideoGameAPI {
	iVideoGameRepository := repository.NewVideoGameRepository(db)
	iVideoGameService := service.NewVideoGameService(iVideoGameRepository)
	videoGameAPI := api.NewVideoGameAPI(iVideoGameService)
	return videoGameAPI
}

func InitConsoleAPI(db *gorm.DB) api.ConsoleAPI {
	iConsoleRepository := repository.NewConsoleRepository(db)
	iConsoleService := service.NewConsoleService(iConsoleRepository)
	consoleAPI := api.NewConsoleAPI(iConsoleService)
	return consoleAPI
}

func InitGraphicsCardAPI(db *gorm.DB) api.GraphicsCardAPI {
	iGraphicsCardRepository := repository.NewGraphicsCardRepository(db)
	iGraphicsCardService := service.NewGraphicsCardService(iGraphicsCardRepository)
	graphicsCardAPI := api.NewGraphicsCardAPI(iGraphicsCardService)
	return graphicsCardAPI
}

func InitProcessorAPI(db *gorm.DB) api.ProcessorAPI {
	iProcessorRepository := repository.NewProcessorRepository(db)
	iProcessorService := service.NewProcessorServiceService(iProcessorRepository)
	processorAPI := api.NewProcessorAPI(iProcessorService)
	return processorAPI
}

func InitMotherboardAPI(db *gorm.DB) api.MotherboardAPI {
	iMotherboardRepository := repository.NewMotherboardRepository(db)
	iMotherboardService := service.NewMotherboardService(iMotherboardRepository)
	motherboardAPI := api.NewMotherboardAPI(iMotherboardService)
	return motherboardAPI
}

func InitRamAPI(db *gorm.DB) api.RamAPI {
	iRamRepository := repository.NewRamRepository(db)
	iRamService := service.NewRamServiceService(iRamRepository)
	ramAPI := api.NewRamAPI(iRamService)
	return ramAPI
}

func InitSolidStateDriveAPI(db *gorm.DB) api.SolidStateDriveAPI {
	iSolidStateDriveRepository := repository.NewSolidStateDriveRepository(db)
	iSolidStateDriveService := service.NewSolidStateDriveService(iSolidStateDriveRepository)
	solidStateDriveAPI := api.NewSolidStateDriveAPI(iSolidStateDriveService)
	return solidStateDriveAPI
}

func InitHardDiskDriveAPI(db *gorm.DB) api.HardDiskDriveAPI {
	iHardDiskDriveRepository := repository.NewHardDiskDriveRepository(db)
	iHardDiskDriveService := service.NewHardDiskDriveService(iHardDiskDriveRepository)
	hardDiskDriveAPI := api.NewHardDiskDriveAPI(iHardDiskDriveService)
	return hardDiskDriveAPI
}

func InitMonitorAPI(db *gorm.DB) api.MonitorAPI {
	iMonitorRepository := repository.NewMonitorRepository(db)
	iMonitorService := service.NewMonitorService(iMonitorRepository)
	monitorAPI := api.NewMonitorAPI(iMonitorService)
	return monitorAPI
}

func InitPowerSupplyUnitAPI(db *gorm.DB) api.PowerSupplyUnitAPI {
	iPowerSupplyUnitRepository := repository.NewPowerSupplyUnitRepository(db)
	iPowerSupplyUnitService := service.NewPowerSupplyUnitService(iPowerSupplyUnitRepository)
	powerSupplyUnitAPI := api.NewPowerSupplyUnitAPI(iPowerSupplyUnitService)
	return powerSupplyUnitAPI
}

func InitKeyboardAPI(db *gorm.DB) api.KeyboardAPI {
	iKeyboardRepository := repository.NewKeyboardRepository(db)
	iKeyboardService := service.NewKeyboardService(iKeyboardRepository)
	keyboardAPI := api.NewKeyboardAPI(iKeyboardService)
	return keyboardAPI
}

func InitMouseAPI(db *gorm.DB) api.MouseAPI {
	iMouseRepository := repository.NewMouseRepository(db)
	iMouseService := service.NewMouseService(iMouseRepository)
	mouseAPI := api.NewMouseAPI(iMouseService)
	return mouseAPI
}

func InitHeadphonesAPI(db *gorm.DB) api.HeadphonesAPI {
	iHeadphonesRepository := repository.NewHeadphonesRepository(db)
	iHeadphonesService := service.NewHeadphonesService(iHeadphonesRepository)
	headphonesAPI := api.NewHeadphonesAPI(iHeadphonesService)
	return headphonesAPI
}
