BASE = "http://localhost:7000"

API = "/api/products/graphicsCards"

GET_ALL = ""
GET_NUMBER_OF_RECORDS = "/getNumberOfRecords"
GET_BY_ID = ""
SEARCH_BY_NAME = "/searchByName"
GET_NUMBER_OF_RECORDS_SEARCH = "/getNumberOfRecordsSearch"
FILTER = "/filter"
GET_NUMBER_OF_RECORDS_FILTER = "/getNumberOfRecordsFilter"
GET_MANUFACTURERS = "/getManufacturers"
GET_CHIP_MANUFACTURERS = "/getChipManufacturers"
GET_MEMORY_SIZES = "/getMemorySizes"
GET_MEMORY_TYPES = "/getMemoryTypes"
GET_MODEL_NAMES = "/getModelNames"

CREATE = ""
UPDATE = ""
DELETE = ""
