BASE = "http://localhost:7000"

API = "/api/products/processors"

GET_ALL = ""
GET_NUMBER_OF_RECORDS = "/getNumberOfRecords"
GET_BY_ID = ""
SEARCH_BY_NAME = "/searchByName"
GET_NUMBER_OF_RECORDS_SEARCH = "/getNumberOfRecordsSearch"
FILTER = "/filter"
GET_NUMBER_OF_RECORDS_FILTER = "/getNumberOfRecordsFilter"
GET_MANUFACTURERS = "/getManufacturers"
GET_SOCKETS = "/getSockets"
GET_TYPES = "/getTypes"
GET_THREADS = "/getThreads"
GET_NUMBER_OF_CORES = "/getNumberOfCores"

CREATE = ""
UPDATE = ""
DELETE = ""
