"""empty message

Revision ID: 5f1ad1b6cddb
Revises: 
Create Date: 2022-07-19 14:25:15.841932

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5f1ad1b6cddb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('verified', sa.Boolean(), nullable=False))
    op.drop_column('users', 'registration_code')
    op.drop_column('users', 'active')
    op.drop_column('users', 'registration_code_expiration_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('registration_code_expiration_date', mysql.DATETIME(), nullable=True))
    op.add_column('users', sa.Column('active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('registration_code', mysql.VARCHAR(length=30), nullable=True))
    op.drop_column('users', 'verified')
    # ### end Alembic commands ###
